# Generated by Django 5.0.6 on 2024-07-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_category_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
    ]
