# Generated by Django 5.0.6 on 2024-07-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_category_description_alter_tag_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
