# Generated by Django 5.0.6 on 2024-07-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
    ]
