# Generated by Django 5.0.6 on 2024-08-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0010_usersettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-due_date"]},
        ),
    ]
