# Generated by Django 5.0.6 on 2024-08-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0011_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["due_date"]},
        ),
    ]
